version: '3.8'

networks:
  personalfit-network:
    driver: bridge
    name: personalfit-network

services:
  postgres:
    image: postgres:15
    container_name: personalfit-db-ngrok
    restart: unless-stopped
    networks:
      - personalfit-network
    environment:
      POSTGRES_DB: personalfit
      POSTGRES_USER: personalfit_user
      POSTGRES_PASSWORD: secret123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  personalfit-backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: personalfit-backend-ngrok
    restart: unless-stopped
    networks:
      - personalfit-network
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/personalfit
      SPRING_DATASOURCE_USERNAME: personalfit_user
      SPRING_DATASOURCE_PASSWORD: secret123
      # Configuración de MercadoPago para el backend
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      # Configuración de conexión de base de datos
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 5
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 2
      # Configuración de Spring Boot para desarrollo
      SPRING_PROFILES_ACTIVE: development
    ports:
      - "8080:8080"
    volumes:
      - comprobantes:/app/comprobantes

  personalfit-frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    container_name: personalfit-frontend-ngrok
    restart: unless-stopped
    networks:
      - personalfit-network
    depends_on:
      - personalfit-backend
    ports:
      - "3000:3000"
    environment:
      # URLs para ngrok (se configurarán dinámicamente)
      NEXT_PUBLIC_API_URL: ${NGROK_URL:-http://localhost:8080}
      NEXT_PUBLIC_BASE_URL: ${NGROK_URL:-http://localhost:3000}
      NEXT_PUBLIC_FRONTEND_URL: ${NGROK_URL:-http://localhost:3000}
      NEXT_PUBLIC_FILES_URL: ${NGROK_URL:-http://localhost:8080}
      
      # Configuración de MercadoPago (sandbox para desarrollo)
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      NEXT_PUBLIC_MP_PUBLIC_KEY: ${NEXT_PUBLIC_MP_PUBLIC_KEY}
      NEXT_PUBLIC_MP_ENVIRONMENT: sandbox
      
      # Configuración de Next.js para desarrollo
      NODE_ENV: development
      NEXT_PUBLIC_IS_DOCKER: "true"

  pgadmin:
    image: dpage/pgadmin4
    container_name: personalfit-pgadmin-ngrok
    restart: unless-stopped
    networks:
      - personalfit-network
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@personalfit.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres

volumes:
  pgdata:
  comprobantes:
