#!/usr/bin/env bash
set -euo pipefail

NO_BUILD=false
SKIP_INSTALL=false

for arg in "$@"; do
  case "$arg" in
    --no-build)
      NO_BUILD=true
      ;;
    --skip-install)
      SKIP_INSTALL=true
      ;;
    *)
      echo "ERROR: opcion desconocida: $arg"
      echo "Uso: ./start-local-dev.sh [--no-build] [--skip-install]"
      exit 1
      ;;
  esac
done

step() {
  echo "==> $1"
}

fail() {
  echo "ERROR: $1" >&2
  exit 1
}

read_env_value() {
  local key="$1"
  local line
  line=$(grep -m1 "^${key}=" "$ROOT_ENV" || true)
  if [[ -n "$line" ]]; then
    printf "%s" "${line#*=}"
  fi
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRONTEND_DIR="$SCRIPT_DIR/Frontend"
ROOT_ENV="$SCRIPT_DIR/.env"
FRONTEND_ENV_LOCAL="$FRONTEND_DIR/.env.local"

cd "$SCRIPT_DIR"

step "Iniciando entorno local con frontend en hot reload"

[[ -f "$ROOT_ENV" ]] || fail "No existe .env en $SCRIPT_DIR"
[[ -f "$SCRIPT_DIR/docker-compose.local.yml" ]] || fail "No existe docker-compose.local.yml en $SCRIPT_DIR"
[[ -d "$FRONTEND_DIR" ]] || fail "No existe el directorio Frontend"

command -v docker >/dev/null 2>&1 || fail "Docker no esta instalado o no esta en PATH"
docker info >/dev/null 2>&1 || fail "Docker daemon no responde. Inicia Docker Desktop"
docker compose version >/dev/null 2>&1 || fail "docker compose no esta disponible"
command -v npm >/dev/null 2>&1 || fail "npm no esta instalado o no esta en PATH"

step "Preparando directorios locales"
mkdir -p local-data/firebase

step "Generando Frontend/.env.local para desarrollo"
api_url="$(read_env_value NEXT_PUBLIC_API_URL)"
api_base_url="$(read_env_value NEXT_PUBLIC_API_BASE_URL)"

if [[ -z "$api_url" ]]; then
  api_url="http://localhost:8080"
fi

if [[ -z "$api_base_url" ]]; then
  api_base_url="$api_url"
fi

{
  echo "# Auto-generated by start-local-dev.sh"
  echo "# Local frontend dev server talking to dockerized backend"
  printf "NEXT_PUBLIC_API_URL=%s\n" "$api_url"
  printf "NEXT_PUBLIC_API_BASE_URL=%s\n" "$api_base_url"
  printf "NEXT_PUBLIC_FIREBASE_API_KEY=%s\n" "$(read_env_value NEXT_PUBLIC_FIREBASE_API_KEY)"
  printf "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=%s\n" "$(read_env_value NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN)"
  printf "NEXT_PUBLIC_FIREBASE_PROJECT_ID=%s\n" "$(read_env_value NEXT_PUBLIC_FIREBASE_PROJECT_ID)"
  printf "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=%s\n" "$(read_env_value NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET)"
  printf "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=%s\n" "$(read_env_value NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID)"
  printf "NEXT_PUBLIC_FIREBASE_APP_ID=%s\n" "$(read_env_value NEXT_PUBLIC_FIREBASE_APP_ID)"
  printf "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=%s\n" "$(read_env_value NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID)"
  printf "NEXT_PUBLIC_FIREBASE_VAPID_KEY=%s\n" "$(read_env_value NEXT_PUBLIC_FIREBASE_VAPID_KEY)"
} > "$FRONTEND_ENV_LOCAL"

step "Levantando Postgres, backend y PgAdmin en Docker"
if [[ "$NO_BUILD" == "true" ]]; then
  docker compose -f docker-compose.local.yml --env-file .env up -d postgres personalfit-backend pgadmin
else
  docker compose -f docker-compose.local.yml --env-file .env up -d --build postgres personalfit-backend pgadmin
fi

step "Deteniendo frontend de Docker si estaba corriendo"
docker compose -f docker-compose.local.yml --env-file .env stop personalfit-frontend >/dev/null 2>&1 || true

if [[ "$SKIP_INSTALL" != "true" && ! -d "$FRONTEND_DIR/node_modules" ]]; then
  step "Instalando dependencias del frontend"
  (
    cd "$FRONTEND_DIR"
    npm install --no-audit --no-fund
  )
fi

step "Generando firebase-messaging-sw.js"
(
  cd "$FRONTEND_DIR"
  npm run generate:sw
)

echo
echo "Servicios Docker activos:"
echo "Backend:  http://localhost:8080/api/health"
echo "PgAdmin:  http://localhost:5050"
echo "Frontend dev: http://localhost:3000"
echo
echo "Para detener Docker luego:"
echo "docker compose -f docker-compose.local.yml --env-file .env down"
echo

step "Ejecutando frontend en modo desarrollo"
cd "$FRONTEND_DIR"
exec npm run dev
